version: '3.8'
services:
  mysql:
    image: 0jacky/telecom:data
    container_name: mysql
    network_mode: "host"
    ports:
      - "3306:3306"
    command: mysql -h 127.0.0.1 --user=$MYSQL_USER --password=$MYSQL_PASS --database=telecom --port=3306
  jupyter:
    image: 0jacky/telecom:data
    build:
      dockerfile: ./dockerfile/data/Dockerfile
      context: .
      args:
        UID: $USERID
        GID: $GROUPID
        USER: $DOCKER_USER
    environment:
      - DOCKER_USER=$DOCKER_USER
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASS=$MYSQL_PASS
      - LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64/
    container_name: jupyter
    network_mode: "host"
    ports:
      - "8888:8888"
      - "3306:3306"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 3
            capabilities: [gpu]
    volumes:
      - $PWD/dockerfile:/home/$DOCKER_USER/telecom/dockerfile
      - $PWD/notebooks:/home/$DOCKER_USER/telecom/notebooks
      - $PWD/data:/home/$DOCKER_USER/telecom/data
      - $PWD/src:/home/$DOCKER_USER/telecom/src
      - /usr/local/cuda-12.2/lib64:/usr/local/cuda-12.2/lib64
    command: jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root
