version: '3.8'
services:
  mysql:
    image: 0jacky/telecom:latest
    container_name: mysql
    network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
      - $PWD/src:/home/$DOCKER_USER/telecom/src
    command: mysql -h 127.0.0.1 --user=$MYSQL_USER --password=$MYSQL_PASS --database=telecom --port=3306
  jupyter-notebook:
    image: 0jacky/telecom:latest
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        UID: $USERID
        GID: $GROUPID
        USER: $DOCKER_USER
      shm_size: '20gb'
      network: host
    cap_add:
      - CAP_SYS_PTRACE
    environment:
      - DOCKER_USER=$DOCKER_USER
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASS=$MYSQL_PASS
      - google_api_key=$google_api_key
      - UCX_TLS=tcp,cuda_copy
    container_name: jupyter
    network_mode: "host"
    ports:
      - "8891:8891"
      - "6666:6666"
      - "3306:3306"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    volumes:
      - $PWD/config:/home/$DOCKER_USER/telecom/config
      - $PWD/notebooks:/home/$DOCKER_USER/telecom/notebooks
      - $PWD/data:/home/$DOCKER_USER/telecom/data
      - $PWD/src:/home/$DOCKER_USER/telecom/src
      - $PWD/report:/home/$DOCKER_USER/telecom/report
      - $PWD/cuda-12.2:/home/$DOCKER_USER/telecom/cuda-12.2
    command: jupyter notebook --ip 0.0.0.0 --port 8891 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    # command: ipython



  preprocess:
    image: 0jacky/telecom:env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASS=$MYSQL_PASS
      - UCX_TLS=tcp,cuda_copy
    container_name: preprocess
    network_mode: "host"
    ports:
      - "3306:3306"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 2
            capabilities: [gpu]
    volumes:
      - $PWD/config:/home/$DOCKER_USER/telecom/config
      - $PWD/data:/home/$DOCKER_USER/telecom/data
      - $PWD/src:/home/$DOCKER_USER/telecom/src
      - $PWD/script:/home/$DOCKER_USER/telecom/script
    command: python script/preprocess.py
    # command: bash
