version: '3.8'
services:
  mysql:
    image: 0jacky/telecom:env
    container_name: mysql
    network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
      - $PWD/src:/home/$DOCKER_USER/telecom/src
    command: mysql -h 127.0.0.1 --user=$MYSQL_USER --password=$MYSQL_PASS --database=telecom --port=3306
  jupyter:
    image: 0jacky/telecom:env
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        UID: $USERID
        GID: $GROUPID
        USER: $DOCKER_USER
      shm_size: '20gb'
      network: host
    cap_add:
      - CAP_SYS_PTRACE
    environment:
      - DOCKER_USER=$DOCKER_USER
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASS=$MYSQL_PASS
      - google_api_key=$google_api_key
    container_name: jupyter
    network_mode: "host"
    ports:
      - "8888:8888"
      - "6666:6666"
      - "3306:3306"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 3
            capabilities: [gpu]
    volumes:
      - $PWD/config:/home/$DOCKER_USER/telecom/config
      - $PWD/notebooks:/home/$DOCKER_USER/telecom/notebooks
      - $PWD/data:/home/$DOCKER_USER/telecom/data
      - $PWD/src:/home/$DOCKER_USER/telecom/src
      - $PWD/report:/home/$DOCKER_USER/telecom/report
    command: jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root
    # command: bash
  preprocess:
    image: 0jacky/telecom:env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASS=$MYSQL_PASS
    container_name: preprocess
    network_mode: "host"
    ports:
      - "3306:3306"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 3
            capabilities: [gpu]
    volumes:
      - $PWD/config:/home/$DOCKER_USER/telecom/config
      - $PWD/data:/home/$DOCKER_USER/telecom/data
      - $PWD/src:/home/$DOCKER_USER/telecom/src
      - $PWD/script:/home/$DOCKER_USER/telecom/script
    command: python script/preprocess.py
    # command: bash
