hydra:
    output_subdir: null
    run:
      dir: .


preprocess:
  mysql_user:
  mysql_pass:
  timeout: 15
  sleep: 1
  db: telecom
  output_dir: data/processed
  month: 201308
  # latlon2addr, create_meta_tower, preprocess, create_edge_attr
  strategy: create_edge_attr
  thres_n_calls: 2
  thres_duration: 0
