hydra:
    output_subdir: null
    run:
      dir: .


preprocess:
  mysql_user:
  mysql_pass:
  timeout: 15
  sleep: 1
  db: telecom
  output_dir: data/processed
  month: 201406
  # latlon2addr, create_meta_tower, preprocess
  strategy: preprocess
