FROM python:3.11.4-bookworm as python-base
WORKDIR /telecom


# no need to create virtual environment since the docker containr is already is
ENV POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_CREATE=false

ENV PATH="$POETRY_HOME/bin:$PATH"

# dependencies to install poetry and set up ODBC
RUN apt-get update && \
    apt-get install --no-install-recommends -y build-essential curl \
    unixodbc odbcinst default-mysql-server odbc-mariadb sshpass

RUN curl -sSL https://install.python-poetry.org | python3 - --version 1.6.0
COPY pyproject.toml poetry.lock ./
RUN poetry install --only data
EXPOSE 8888


# set up ODBC
COPY docker/utils/odbcinst.ini /etc/odbcinst.ini
COPY docker/utils/ssh_config /etc/ssh/ssh_config

RUN mkdir -p /data/processed
CMD ["bash"]
